---
title: "Assignment 2"
author: "Robert Evans"
date: "March 26, 2017"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#4.1- Building Decision Trees with Package party
This section goes over how to build a decision tree using the party package
```{r}
#install.packages("party")

#view the iris data set
str(iris)

#set a seed for repeatable results
set.seed(1234)

#build test and training set with a 70/30 split
ind <- sample(2, nrow(iris), replace=TRUE, prob=c(0.7,0.3))
trainData <- iris[ind==1,]
testData <- iris[ind==2,]

#Load the party package, build a tree and check the prediction
library(party)
myFormula <- Species~Sepal.Length + Sepal.Width + Petal.Length + Petal.Width
iris_ctree <- ctree(myFormula, data=trainData)
#check the prediction
table(predict(iris_ctree), trainData$Species)

#print a text version of the tree
print(iris_ctree)

#graphic tree
plot(iris_ctree)

plot(iris_ctree, type="simple")

#predictions on test data
testPred <- predict(iris_ctree, newdata = testData)
table(testPred, testData$Species)
```

